export default{
    GET_GROUPED_TRIPS: "GET_GROUPED_TRIPS",
    TRIPS_IS_LOADING: "TRIPS_IS_LOADING",
    ASSIGN_FCM_TOKEN: "ASSIGN_FCM_TOKEN",
    UNASSIGN_FCM_TOKEN: "UNASSIGN_FCM_TOKEN",
    ON_TRIP_NOTIFICATION: "ON_TRIP_NOTIFICATION",
    NOTIFICATION_TRIP_IS_LOADING: "NOTIFICATION_TRIP_IS_LOADING",
    GET_NOTIFICATION_TRIP_DATA: "GET_NOTIFICATION_TRIP_DATA",
    CLOSE_TRIP_NOTIFICATION: "CLOSE_TRIP_NOTIFICATION",
    NOTIFICATION_ACCEPT_TRIP: "NOTIFICATION_ACCEPT_TRIP",
    NOTIFICATION_DECLINE_TRIP: "NOTIFICATION_DECLINE_TRIP"
}