export default{
    GET_TRIP_DATA: "GET_TRIP_DATA",
    ACCEPT_TRIP: "ACCEPT_TRIP",
    ON_ROUTE: "ON_ROUTE",
    GET_PASSENGER: "GET_PASSENGER",
    COMPLETE_TRIP: "COMPLETE_TRIP",
    END_TRIP: "END_TRIP"
}